### ISSUE TITLE
Traceback after retry

### ISSUE THREAD

**Issue by chris-y** [chris-y/bgg-to-neodb#2]
waiting 5s for response
Traceback (most recent call last):
  File "/media/nas/git-repos/bgg-to-neodb/./bgg.py", line 66, in <module>
    bgg_coll = get_bgg_collection(a['bgguser'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nas/git-repos/bgg-to-neodb/./bgg.py", line 31, in get_bgg_collection
    while r.status_code != 200:
          ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'status_code'

**Comment by chris-y** [comment]
waiting 5s for response
Traceback (most recent call last):
  File "/media/nas/git-repos/bgg-to-neodb/./bgg.py", line 135, in <module>
    bgg_to_neodb_collection(a['bgguser'], app)
  File "/media/nas/git-repos/bgg-to-neodb/./bgg.py", line 78, in bgg_to_neodb_collection
    bgg_coll = get_bgg_collection(user)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/nas/git-repos/bgg-to-neodb/./bgg.py", line 47, in get_bgg_collection
    r = get_bgg_coll(user)
        ^^^^^^^^^^^^^^^^^^
  File "/media/nas/git-repos/bgg-to-neodb/./bgg.py", line 35, in get_bgg_coll
    while r.status_code != 200:
          ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'status_code'
